accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/' , views.user_register , name = 'user_register'),
    path('login/' , views.user_login , name = 'login'),
    path('logout/' , views.user_logout , name ='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('home.urls', namespace='home')),
    # path("templates/", include("django.contrib.auth.urls")),
    path('accounts/', include('accounts.urls', namespace='accounts')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('' , views.home , name = 'home') ,
]

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
class UserRegisterForm(forms.Form):
    user_name = (
        forms.CharField(max_length=50 ,
    widget=forms.TextInput(attrs={'placeholder' : 'نام کاربری خود را وارد نمایید'})))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder' : 'email....'}))
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    password_1 = (
        forms.CharField(max_length=100 ,
                        widget=forms.PasswordInput(attrs={'placeholder' : 'پسورد ...'})))
    password_2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'placeholder' : 'تکرار پسورد ...'}))

    def clean_user_name(self):
        user = self.cleaned_data['user_name']
        if User.objects.filter(username = user).exists():
            raise forms.ValidationError('نام کاربری تکرای است')
        return user

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).exists():
            raise forms.ValidationError('ایمیل تکراری است')
        return email

    def clean_password_2(self):
        password1 = self.cleaned_data['password_1']
        password2 = self.cleaned_data['password_2']
        if password1 != password2 :
            raise forms.ValidationError('Password not match')
        elif len(password2) < 8 :
            raise forms.ValidationError('پسورد می بایست حداقل 8 کارکتر باشد')
        elif not any(x.isupper() for x in password2):
            raise forms.ValidationError('پسورد می بایست شامل حداقل یک حرف بزرگ باشد')
        return password2


class UserLoginForm(forms.Form):
    user = forms.CharField()
    password = forms.CharField()

accounts/views.py
from django.shortcuts import render , redirect
from .forms import UserRegisterForm , UserLoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login , logout
from django.contrib import messages
# Create your views here.

def user_register(request):
    if request.method == 'POST' :
        form = UserRegisterForm(request.POST)
        if form.is_valid() :
            data = form.cleaned_data
            User.objects.create_user(
                username = data['user_name'] ,
                email = data['email'] ,
                first_name = data['first_name'],
                last_name = data['last_name'] ,
                password = data['password_2']
            )
            messages.success(request , 'ثبت نام شما با موفقیت انجام شد'  ,'success')
            return redirect('home:home')
    else :
        form = UserRegisterForm()
    return render(request , 'accounts/register.html',{'form':form})




def user_login(request) :
    if request.method == 'POST' :
        form = UserLoginForm(request.POST)
        if form.is_valid() :
            data = form.cleaned_data
            user = authenticate(request ,
                                username = data['user'] , password = data['password'])
            if user is not None :
                login(request , user)
                messages.success(request , 'خوش آمدید' , 'primary')
                return redirect('home:home')
            else:
                messages.error(request , 'نام کاربری یا رمز عبور اشتباه است' , 'danger')

    else :
        form = UserLoginForm()
    return render(request,'accounts/login.html',{'form':form})

def user_logout(request):
    logout(request)
    messages.success(request,'به امید دیدار' , 'info')
    return redirect('home:home')

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request , 'home/home.html')

accounts/templates/accounts/login.html
{% extends '_base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}
	ورود کاربر
{% endblock %}
{% block body %}
	<form method="post">

        {% csrf_token %}
        {% bootstrap_form form %}

        <input type="text" name="user" placeholder="نام کاربری ...">
        <input type="password" name="password" placeholder="رمز عبور ...">
        <button type="submit">Login</button>
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends '_base.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block title %}
    صفحه ایجاد کاربر
{% endblock %}
{% block body %}
    <form method="post" novalidate>
        {% csrf_token %}

        {% bootstrap_form form %}
        <button type="submit">Register</button>
    </form>
{% endblock %}

home/templates/home/home.html
{% extends '_base.html' %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}

{% block title %}
	صفحه اصلی
{% endblock %}
{% block body %}
	<h1>به وب سایت من خوش آمدید</h1>
{% endblock %}

templates/_base.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
<title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q" crossorigin="anonymous">

</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% include 'message.html' %}
    {% block body %}

    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>
</html>

templates/_base_back.html
<!DOCTYPE html>
<html dir="rtl" lang="fa">
<head>
  {% block title %}{% endblock %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<div class="container">


    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/message.html
{% if messages %}
    {% for msg in messages %}
        <h3 {% if msg.tags %} class="alert alert-{{ msg.tags }}" {% endif %}>{{ msg }}</h3>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"
                       href="{% url 'home:home' %}">صفحه اصلی</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a>
                    </li>
                {% else %}

                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'accounts:login' %}">ورود</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link "
                           href="{% url 'accounts:user_register' %}">ثبت نام</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>